version: '3'

services:
  web:
    build: .
    command: /code/django_setup.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db

  db:
    image: kartoza/postgis:12.0
    env_file:
      - ./.env_postgis
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432